#!/usr/bin/env bash
#
# FMU Platform — Staging Environment Setup
#
# Generates .env.staging with its own passwords, isolated from production.
#
set -euo pipefail

gen_hex() { openssl rand -hex "$1"; }

info()  { echo "  ✓ $1"; }
warn()  { echo "  ⚠ $1"; }

PG_PASS=$(gen_hex 16)
REDIS_PASS=$(gen_hex 16)
SECRET_KEY=$(gen_hex 32)

echo ""
echo "FMU Platform — Staging Setup"
echo "============================"
echo ""

read -rp "  Staging subdomain (e.g. staging.fmu.example.com) [staging.localhost]: " DOMAIN
DOMAIN=${DOMAIN:-staging.localhost}

read -rp "  Number of AMESim licenses for staging [1]: " LICENSE_COUNT
LICENSE_COUNT=${LICENSE_COUNT:-1}

if [ "$DOMAIN" = "staging.localhost" ]; then
  CADDY_DOMAIN=":8080"
  CORS_ORIGINS="http://localhost:5174,http://localhost:3001"
else
  CADDY_DOMAIN="$DOMAIN"
  DEFAULT_CORS="https://$DOMAIN"
  read -rp "  CORS origins (comma-separated) [$DEFAULT_CORS]: " CORS_ORIGINS
  CORS_ORIGINS=${CORS_ORIGINS:-$DEFAULT_CORS}
fi

ENV_FILE=".env.staging"

if [ -f "$ENV_FILE" ]; then
  warn ".env.staging already exists — backing up"
  cp "$ENV_FILE" ".env.staging.backup.$(date +%s)"
fi

cat > "$ENV_FILE" <<EOF
# ┌──────────────────────────────────────────────────────────────────────┐
# │  STAGING — Auto-generated by setup-staging.sh                      │
# │  on $(date -u +"%Y-%m-%d %H:%M:%S UTC")                                      │
# └──────────────────────────────────────────────────────────────────────┘

# === Domain ===
# STAGING_DOMAIN is read by Caddy (via the Caddyfile)
STAGING_DOMAIN=$CADDY_DOMAIN

# === PostgreSQL (separate from production) ===
POSTGRES_DB=fmu_platform_staging
POSTGRES_USER=fmu
POSTGRES_PASSWORD=$PG_PASS

# === Redis ===
REDIS_PASSWORD=$REDIS_PASS

# === Backend ===
DATABASE_URL=postgresql+asyncpg://fmu:${PG_PASS}@postgres-staging/fmu_platform_staging
DATABASE_URL_SYNC=postgresql://fmu:${PG_PASS}@postgres-staging/fmu_platform_staging
REDIS_URL=redis://:${REDIS_PASS}@redis-staging:6379/0

# === License Management (fewer licenses for staging) ===
LICENSE_POOL_SIZE=$LICENSE_COUNT

# === Storage Paths ===
FMU_LIBRARY_PATH=/opt/fmu-platform/fmu-library
PROJECTS_PATH=/opt/fmu-platform/projects
TEMP_PATH=/opt/fmu-platform/temp

# === Auth ===
SECRET_KEY=$SECRET_KEY
ACCESS_TOKEN_EXPIRE_MINUTES=60

# === CORS ===
CORS_ORIGINS=$CORS_ORIGINS
EOF

info ".env.staging created"

# Also update STAGING_DOMAIN in production .env so Caddy routes to it
if [ -f ".env" ]; then
  if grep -q "^STAGING_DOMAIN=" .env; then
    sed -i "s|^STAGING_DOMAIN=.*|STAGING_DOMAIN=$CADDY_DOMAIN|" .env
  else
    echo "" >> .env
    echo "STAGING_DOMAIN=$CADDY_DOMAIN" >> .env
  fi
  info "STAGING_DOMAIN=$CADDY_DOMAIN added to .env (for Caddy)"
else
  warn ".env not found — run ./setup.sh first, then re-run this script"
fi

echo ""
echo "  ┌──────────────────────────────────────────────┐"
echo "  │  Staging setup complete                      │"
echo "  ├──────────────────────────────────────────────┤"
echo "  │  Domain:     $DOMAIN"
echo "  │  DB name:    fmu_platform_staging"
echo "  │  Licenses:   $LICENSE_COUNT"
echo "  └──────────────────────────────────────────────┘"
echo ""
echo "  Next: ./deploy-staging.sh"
echo ""
