#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "⚠  .env already exists. Remove it first to regenerate."
    exit 1
fi

gen() { openssl rand -hex "$1"; }

PG_PASS=$(gen 16)
REDIS_PASS=$(gen 16)
SECRET_KEY=$(gen 32)

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — edit as needed

# PostgreSQL
POSTGRES_DB=fmu_platform
POSTGRES_USER=fmu
POSTGRES_PASSWORD=$PG_PASS

# Redis
REDIS_PASSWORD=$REDIS_PASS

# Backend
DATABASE_URL=postgresql://fmu:$PG_PASS@postgres/fmu_platform
REDIS_URL=redis://:$REDIS_PASS@redis:6379/0

# License management
LICENSE_POOL_SIZE=3

# Storage (inside containers)
FMU_LIBRARY_PATH=/opt/fmu-platform/fmu-library
PROJECTS_PATH=/opt/fmu-platform/projects
TEMP_PATH=/opt/fmu-platform/temp

# Auth
SECRET_KEY=$SECRET_KEY
ACCESS_TOKEN_EXPIRE_MINUTES=60

# CORS — update with your domain
CORS_ORIGINS=["http://localhost:5173"]
EOF

echo "✓ .env created with generated secrets."
echo ""
echo "Next steps:"
echo "  1. Edit CORS_ORIGINS if you have a domain"
echo "  2. docker compose up -d"
