#!/usr/bin/env bash
#
# FMU Platform — Environment Setup
#
# Usage:
#   ./setup.sh                    Interactive setup (asks for domain, license count, etc.)
#   ./setup.sh --defaults         Use all defaults (localhost, 3 licenses)
#
set -euo pipefail

# ── Helpers ──────────────────────────────────────────────────────────────────

gen_hex() { openssl rand -hex "$1"; }

info()  { echo "  ✓ $1"; }
warn()  { echo "  ⚠ $1"; }

# ── Parse flags ──────────────────────────────────────────────────────────────

USE_DEFAULTS=false

for arg in "$@"; do
  case "$arg" in
    --defaults) USE_DEFAULTS=true ;;
    --help|-h)
      echo "Usage: ./setup.sh [--defaults]"
      echo "  --defaults   Skip prompts, use default values"
      exit 0
      ;;
  esac
done

# ── Generate secrets ─────────────────────────────────────────────────────────

PG_PASS=$(gen_hex 16)
REDIS_PASS=$(gen_hex 16)
SECRET_KEY=$(gen_hex 32)

echo ""
echo "FMU Platform — Environment Setup"
echo "================================"
echo ""

# ── Gather config (interactive or defaults) ──────────────────────────────────

if [ "$USE_DEFAULTS" = true ]; then
  DOMAIN="localhost"
  CADDY_DOMAIN=":80"
  LICENSE_COUNT=3
  CORS_ORIGINS="http://localhost:5173,http://localhost:3000"
else
  read -rp "  Domain (or 'localhost' for local dev) [localhost]: " DOMAIN
  DOMAIN=${DOMAIN:-localhost}

  read -rp "  Number of AMESim licenses available [3]: " LICENSE_COUNT
  LICENSE_COUNT=${LICENSE_COUNT:-3}

  if [ "$DOMAIN" = "localhost" ]; then
    CADDY_DOMAIN=":80"  # Plain HTTP, no TLS
    CORS_ORIGINS="http://localhost:5173,http://localhost:3000"
  else
    CADDY_DOMAIN="$DOMAIN"  # Caddy auto-HTTPS with Let's Encrypt
    DEFAULT_CORS="https://$DOMAIN"
    read -rp "  CORS origins (comma-separated) [$DEFAULT_CORS]: " CORS_ORIGINS
    CORS_ORIGINS=${CORS_ORIGINS:-$DEFAULT_CORS}
  fi
fi

echo ""

# ── Write .env ───────────────────────────────────────────────────────────────

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — backing up to .env.backup"
  cp "$ENV_FILE" ".env.backup.$(date +%s)"
fi

cat > "$ENV_FILE" <<EOF
# ┌──────────────────────────────────────────────────────────────────────┐
# │  Auto-generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")           │
# │  Edit as needed, but DO NOT commit this file to git.                │
# └──────────────────────────────────────────────────────────────────────┘

# === Domain (used by Caddy for automatic HTTPS) ===
# ":80" = plain HTTP (no domain), "fmu.example.com" = auto HTTPS
DOMAIN=$CADDY_DOMAIN

# === Staging domain (set by setup-staging.sh, leave empty to disable) ===
STAGING_DOMAIN=

# === PostgreSQL ===
POSTGRES_DB=fmu_platform
POSTGRES_USER=fmu
POSTGRES_PASSWORD=$PG_PASS

# === Redis ===
REDIS_PASSWORD=$REDIS_PASS

# === Backend ===
DATABASE_URL=postgresql+asyncpg://fmu:${PG_PASS}@postgres/fmu_platform
DATABASE_URL_SYNC=postgresql://fmu:${PG_PASS}@postgres/fmu_platform
REDIS_URL=redis://:${REDIS_PASS}@redis:6379/0

# === License Management ===
LICENSE_POOL_SIZE=$LICENSE_COUNT

# === Storage Paths (inside containers) ===
FMU_LIBRARY_PATH=/opt/fmu-platform/fmu-library
PROJECTS_PATH=/opt/fmu-platform/projects
TEMP_PATH=/opt/fmu-platform/temp

# === Auth ===
SECRET_KEY=$SECRET_KEY
ACCESS_TOKEN_EXPIRE_MINUTES=60

# === CORS ===
CORS_ORIGINS=$CORS_ORIGINS
EOF

info ".env created with generated secrets"

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "  ┌──────────────────────────────────────────────┐"
echo "  │  Setup complete                              │"
echo "  ├──────────────────────────────────────────────┤"
echo "  │  Domain:        $DOMAIN"
echo "  │  PG password:   ${PG_PASS:0:8}..."
echo "  │  Redis password: ${REDIS_PASS:0:8}..."
echo "  │  Secret key:    ${SECRET_KEY:0:8}..."
echo "  │  License slots: $LICENSE_COUNT"
echo "  │  CORS origins:  $CORS_ORIGINS"
echo "  └──────────────────────────────────────────────┘"
echo ""
echo "  Next steps:"
echo "    1. docker compose up -d --build"

if [ "$DOMAIN" != "localhost" ]; then
  echo "    2. Make sure DNS for $DOMAIN points to this server"
  echo "    3. Caddy will automatically get an HTTPS certificate"
  echo "    4. Open https://$DOMAIN/api/docs"
else
  echo "    2. Open http://localhost:8000/api/docs"
fi

echo ""
